server {
    listen 80;
    server_name stg.quanhomeserver.online;

    location / {
        proxy_pass http://fruitshop-fe-test:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        proxy_pass http://fruitshop-be-test:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
